version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - ./test.py:/app/test.py
    depends_on:
      - server