version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5000:5000"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 3

  test:
    build:
      context: .
      dockerfile: test.Dockerfile
    volumes:
      - ./test.py:/app/test.py
    depends_on:
      selenium:
        condition: service_healthy